### ISSUE TITLE
Can't depend on noli from app

### ISSUE THREAD

**Issue by d0iasm** [hikalium/wasabi#14]
No such file or directory error happens when an app depends on noli because generated/ directory is not generated if wasabi is used as a library.

```
// Cargo.toml

[dependencies]
noli = { git = "https://github.com/hikalium/wasabi.git", optional = true }
```

Error:

```
error: couldn't read ~/.cargo/git/checkouts/wasabi-03f40552360a1354/e9ace5f/noli/src/../../generated/font.rs: No such file or directory (os error 2)
 --> ~/.cargo/git/checkouts/wasabi-03f40552360a1354/e9ace5f/noli/src/font.rs:1:1
  |
1 | include!("../../generated/font.rs");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `include` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by hikalium** [comment]
Ah, please run `make font` on the wasabi's root dir to make it work...
(Sorry)

2023年12月30日(土) 21:45 Asami ***@***.***>:

**Comment by d0iasm** [comment]
```
$ cd ~/.cargo/git/checkouts/wasabi-03f40552360a1354/e9ace5f/
$ make
```

It solves the error but I think it's better not to use `include!` because `make` command isn't executed when it's used as a library.

**Comment by hikalium** [comment]
Let me fix that by calling make from build.rs of noli to build the generated font.rs correctly.

**Comment by d0iasm** [comment]
Thanks so much 😊
