### ISSUE TITLE
`make run` fails on Mac

### ISSUE THREAD

**Issue by d0iasm** [hikalium/wasabi#20]
`make run` fails on Mac because find command doesn't have `-executable` flag on Mac OS.

```
cp `find target/x86_64-unknown-none/release -maxdepth 1 -executable -type f` generated/bin/
find: -executable: unknown primary or operator
```

It looks `-executable` is only supported on GNU.
https://stackoverflow.com/questions/4458120/search-for-executable-files-using-find-command

**Comment by d0iasm** [comment]
Replacing `-executable` with `-perm 755` works well on Mac.

**Comment by hikalium** [comment]
Removed all the usage of find commands, and improved the build speed by utilizing cargo more. Thanks for finding the issue!
